# Generated by Django 6.0.2 on 2026-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delinquency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_id', models.CharField(db_index=True, max_length=100)),
                ('borrower_name', models.CharField(max_length=255)),
                ('dpd', models.PositiveIntegerField()),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bucket', models.CharField(choices=[('0-30', '0-30 DPD'), ('31-60', '31-60 DPD'), ('61-90', '61-90 DPD'), ('90+', '90+ DPD (NPA)')], max_length=10)),
                ('action_type', models.CharField(choices=[('CALL', 'Call Borrower'), ('VISIT', 'Field Visit'), ('LEGAL', 'Legal Notice'), ('SETTLED', 'Settled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['loan_account_id'], name='loan_collec_loan_ac_0d4a8f_idx'), models.Index(fields=['bucket'], name='loan_collec_bucket_dd9374_idx')],
            },
        ),
    ]
