# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='0000000000', max_length=20)),
                ('bank_name', models.CharField(default='Unknown Bank', max_length=255)),
                ('ifsc_code', models.CharField(default='UNKNOWNIFSC', max_length=11)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('penny_drop_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('enach_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
