# Generated by Django 4.2.7 on 2026-01-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='ifsc_code',
        ),
    ]
