# Generated by Django 4.2.7 on 2026-01-07 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_remove_mandate_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mandate',
            name='bank_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the bank associated with the mandate', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='mandate',
            table='banking_mandate',
        ),
    ]
