# Generated by Django 4.2.7 on 2026-01-07 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_mandate_options_mandate_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandate',
            options={},
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='failure_reason',
        ),
        migrations.AlterField(
            model_name='mandate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='enach_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Not Registered'), ('REGISTERED', 'Registered'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_REGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='penny_drop_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='mandate',
            table=None,
        ),
    ]
