# Generated by Django 4.2.7 on 2026-01-08 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0003_alter_propertydetail_property_type'),
        ('banking', '0005_alter_mandate_options_remove_mandate_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='enach_status',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='penny_drop_status',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='mandate',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='los.loanapplication'),
        ),
    ]
