# Generated by Django 4.2.7 on 2026-01-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0004_alter_bankdetail_account_number_and_more'),
        ('banking', '0006_remove_mandate_enach_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mandate',
            name='status',
        ),
        migrations.AddField(
            model_name='mandate',
            name='enach_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='mandate',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='penny_drop_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='mandate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandate', to='los.loanapplication'),
        ),
    ]
