# Generated by Django 4.2.7 on 2026-01-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_remove_mandate_created_at_remove_mandate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='enach_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'fail')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='penny_drop_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'fail')], default='PENDING', max_length=10),
        ),
    ]
