# Generated by Django 6.0.1 on 2026-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_mandate_enach_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='action',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'fail')], default='PENDING', max_length=10),
        ),
    ]
