# Generated by Django 4.2.7 on 2026-01-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('los', '0003_alter_propertydetail_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursed_at', models.DateTimeField(auto_now_add=True)),
                ('utr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='los.loanapplication')),
            ],
        ),
    ]
