# Generated by Django 4.2.7 on 2026-01-08 08:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement',
            old_name='disbursed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='application',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='utr_number',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='loan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
