# Generated by Django 4.2.7 on 2026-01-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_mandate_options_remove_mandate_bank_name_and_more'),
        ('disbursement', '0002_rename_disbursed_at_disbursement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='loan',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='mandate',
            field=models.ForeignKey(blank=True, limit_choices_to={'loan_application__status': 'success'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.mandate'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
