# Generated by Django 4.2.7 on 2026-01-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_remove_mandate_enach_status_and_more'),
        ('disbursement', '0003_remove_disbursement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='mandate',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'SUCCESS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='banking.mandate'),
        ),
    ]
