# Generated by Django 4.2.7 on 2026-01-08 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0004_alter_bankdetail_account_number_and_more'),
        ('disbursement', '0004_alter_disbursement_mandate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='disbursement_date',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='mandate',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='status',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursement',
            name='enach_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='loan_application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='los.loanapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursement',
            name='penny_drop_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
