# Generated by Django 6.0.2 on 2026-02-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement', models.UUIDField(unique=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
