# Generated by Django 6.0.2 on 2026-02-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0005_remove_disbursement_disbursement_date_and_more'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='disbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_account', to='disbursement.disbursement'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=50),
        ),
    ]
