# Generated by Django 6.0.2 on 2026-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_loanaccount_disbursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='action',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=50),
        ),
    ]
