# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.db import migrations, models
import django.db.models.deletion
import los.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='0000000000', max_length=20)),
                ('ifsc_code', models.CharField(default='UNKNOWNIFSC', max_length=11)),
                ('bank_name', models.CharField(default='Unknown Bank', max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('penny_drop_status', models.CharField(default='PENDING', max_length=20)),
                ('enach_status', models.CharField(default='NOT_REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SYSTEM_APPROVED', 'System Approved'), ('SYSTEM_REJECTED', 'System Rejected'), ('MANUAL_APPROVED', 'Manual Approved'), ('MANUAL_REJECTED', 'Manual Rejected')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_assessments',
            },
        ),
        migrations.CreateModel(
            name='KYCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('BANK_STATEMENT', 'Bank Statement'), ('SALARY_SLIP', 'Salary Slip'), ('ITR', 'ITR'), ('GST', 'GST'), ('SALE_DEED', 'Sale Deed'), ('ENCUMBRANCE_CERT', 'Encumbrance Certificate')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc/')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kyc_details',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application_number', models.CharField(default=los.models.generate_application_number, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('KNOCKOUT_PENDING', 'Knockout Checks'), ('DOC_UPLOAD', 'Document Upload'), ('UNDERWRITING', 'Underwriting'), ('HOLD', 'On Hold'), ('SANCTIONED', 'Sanctioned'), ('PRE_DISBURSEMENT', 'Pre Disbursement'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=30)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_tenure', models.IntegerField(help_text='Months')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('borrower_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PARTNERSHIP', 'Partnership Firm'), ('CORPORATE', 'Corporate')], max_length=20)),
                ('income_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('res_address_line1', models.CharField(max_length=255)),
                ('res_city', models.CharField(max_length=100)),
                ('res_state', models.CharField(max_length=100)),
                ('res_pincode', models.CharField(max_length=6)),
                ('office_address_line1', models.CharField(blank=True, max_length=255)),
                ('office_city', models.CharField(blank=True, max_length=100)),
                ('office_pincode', models.CharField(blank=True, max_length=6)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.branch')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_detail', to='los.loanapplication')),
            ],
            options={
                'db_table': 'property_details',
            },
        ),
        migrations.CreateModel(
            name='MortgageUnderwriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ltv_on_property', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_eligible_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_underwriting', to='los.loanapplication')),
            ],
            options={
                'db_table': 'mortgage_underwriting',
            },
        ),
    ]
