# Generated by Django 4.2.7 on 2026-01-02 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0002_initial'),
        ('crm', '0002_initial'),
        ('los', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminpanel.loanproduct'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='los.loanapplication'),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_assessment', to='los.loanapplication'),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='los.loanapplication'),
        ),
    ]
