# Generated by Django 4.2.7 on 2026-01-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat / Apartment'), ('PLOT', 'Plot / Land'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial Property')], max_length=30),
        ),
    ]
