# Generated by Django 4.2.7 on 2026-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0003_alter_propertydetail_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
    ]
