# Generated by Django 6.0.1 on 2026-02-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0004_alter_bankdetail_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='borrower_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income_type',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='pan_number',
        ),
    ]
