# Generated by Django 6.0.1 on 2026-02-02 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0005_remove_loanapplication_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_type',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
